// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom3_CongTyVanChuyen.Data;

#nullable disable

namespace Nhom3_CongTyVanChuyen.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250521104701_b")]
    partial class b
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaChiTietDonHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHangHoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("TrongLuong")
                        .HasColumnType("float");

                    b.HasKey("MaChiTietDonHang");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaHangHoa");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.DanhMuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.DonHang", b =>
                {
                    b.Property<string>("MaDonHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HanNopTienThuHo")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVanDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<double>("PhiGiaoHang")
                        .HasColumnType("float");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TienThuHo")
                        .HasColumnType("float");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThuHo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.HangHoa", b =>
                {
                    b.Property<string>("MaHangHoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TinhChatHangHoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHangHoa");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaSoNha");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NguoiNhan", b =>
                {
                    b.Property<string>("MaNguoiNhan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiNhan");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaSoNha");

                    b.ToTable("NguoiNhans");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaSoNha");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NhanVienThongBao", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaThongBao")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNhanVien", "MaThongBao");

                    b.HasIndex("MaThongBao");

                    b.ToTable("NhanVienThongBaos");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.PhuongXa", b =>
                {
                    b.Property<string>("MaPhuongXa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenPhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhuongXa");

                    b.HasIndex("MaQuanHuyen");

                    b.ToTable("PhuongXas");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.QuanHuyen", b =>
                {
                    b.Property<string>("MaQuanHuyen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTinhTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQuanHuyen");

                    b.HasIndex("MaTinhTP");

                    b.ToTable("QuanHuyens");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.SoNha", b =>
                {
                    b.Property<string>("MaSoNha")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChiSoNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhuongXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaSoNha");

                    b.HasIndex("MaPhuongXa");

                    b.ToTable("SoNhas");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.ThongBao", b =>
                {
                    b.Property<string>("MaThongBao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThongBao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.TinhThanhPho", b =>
                {
                    b.Property<string>("MaTinhTP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTinhTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinhTP");

                    b.ToTable("TinhThanhPhos");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.VaiTro", b =>
                {
                    b.Property<string>("MaVaiTro")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.ChiTietDonHang", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom3_CongTyVanChuyen.Data.HangHoa", "HangHoa")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaHangHoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.DonHang", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom3_CongTyVanChuyen.Data.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.HangHoa", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.DanhMuc", "DanhMuc")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.KhachHang", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.SoNha", "SoNha")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaSoNha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SoNha");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NguoiNhan", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.KhachHang", "KhachHang")
                        .WithMany("NguoiNhans")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom3_CongTyVanChuyen.Data.SoNha", "SoNha")
                        .WithMany("NguoiNhans")
                        .HasForeignKey("MaSoNha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SoNha");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NhanVien", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.SoNha", "SoNha")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaSoNha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom3_CongTyVanChuyen.Data.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SoNha");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NhanVienThongBao", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom3_CongTyVanChuyen.Data.ThongBao", "ThongBao")
                        .WithMany("NhanVienThongBaos")
                        .HasForeignKey("MaThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.PhuongXa", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.QuanHuyen", "QuanHuyen")
                        .WithMany("PhuongXas")
                        .HasForeignKey("MaQuanHuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.QuanHuyen", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.TinhThanhPho", "TinhThanhPho")
                        .WithMany("QuanHuyens")
                        .HasForeignKey("MaTinhTP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TinhThanhPho");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.SoNha", b =>
                {
                    b.HasOne("Nhom3_CongTyVanChuyen.Data.PhuongXa", "PhuongXa")
                        .WithMany("SoNhas")
                        .HasForeignKey("MaPhuongXa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.DanhMuc", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.HangHoa", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("NguoiNhans");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.NhanVien", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.PhuongXa", b =>
                {
                    b.Navigation("SoNhas");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.QuanHuyen", b =>
                {
                    b.Navigation("PhuongXas");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.SoNha", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NguoiNhans");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.ThongBao", b =>
                {
                    b.Navigation("NhanVienThongBaos");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.TinhThanhPho", b =>
                {
                    b.Navigation("QuanHuyens");
                });

            modelBuilder.Entity("Nhom3_CongTyVanChuyen.Data.VaiTro", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
